// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/kJBABOTEQl9
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */
//
// /** Add fonts into your Next.js project:
//
// import { Inter } from 'next/font/google'
//
// inter({
//   subsets: ['latin'],
//   display: 'swap',
// })
//
// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link"
//
// export function MainSideBar() {
//   return (
//     <>
//       <header className="flex items-center justify-between bg-white px-4 py-3 text-gray-900 shadow-lg">
//         <div className="flex items-center gap-4">
//           <button
//             className="rounded-md p-2 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-gray-500"
//             data-collapsed="false"
//           >
//             <MenuIcon className="h-6 w-6" />
//           </button>
//           <Link className="text-lg font-medium" href="#">
//             Dashboard
//           </Link>
//         </div>
//         <div className="flex items-center gap-4">
//           <Link className="relative" href="#">
//             <BellIcon className="h-6 w-6" />
//             <span className="absolute -top-2 -right-2 rounded-full bg-red-500 px-2 py-1 text-xs font-medium text-white">
//               3
//             </span>
//           </Link>
//           <Link className="flex items-center gap-2" href="#">
//             <img
//               alt="Avatar"
//               className="rounded-full"
//               height="32"
//               src="/placeholder.svg"
//               style={{
//                 aspectRatio: "32/32",
//                 objectFit: "cover",
//               }}
//               width="32"
//             />
//             <span className="text-sm font-medium">John Doe</span>
//           </Link>
//         </div>
//       </header>
//       <div className="relative flex h-screen w-full">
//         <div className="fixed left-0 top-0 z-10 h-full w-16 bg-white text-gray-900 shadow-lg transition-all duration-300 ease-in-out data-[collapsed=true]:w-4">
//           <nav className="flex h-full flex-col items-center justify-between py-4">
//             <div className="flex flex-col items-center gap-6">
//               <Link className="group relative" href="#">
//                 <HomeIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Home
//                 </span>
//               </Link>
//               <Link className="group relative" href="#">
//                 <LayoutDashboardIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Dashboard
//                 </span>
//               </Link>
//               <Link className="group relative" href="#">
//                 <ProjectorIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Projects
//                 </span>
//               </Link>
//               <Link className="group relative" href="#">
//                 <ActivityIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Tasks
//                 </span>
//               </Link>
//               <Link className="group relative" href="#">
//                 <CalendarIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Calendar
//                 </span>
//               </Link>
//               <Link className="group relative" href="#">
//                 <SettingsIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Settings
//                 </span>
//               </Link>
//             </div>
//             <div className="flex flex-col items-center gap-6">
//               <Link className="group relative" href="#">
//                 <UserIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Profile
//                 </span>
//               </Link>
//               <Link className="group relative" href="#">
//                 <LogOutIcon className="h-6 w-6" />
//                 <span className="absolute left-20 top-0 z-10 w-max rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-900 opacity-0 transition-all group-hover:opacity-100 data-[collapsed=true]:hidden">
//                   Logout
//                 </span>
//               </Link>
//             </div>
//           </nav>
//           <button
//             className="absolute right-0 top-1/2 -translate-y-1/2 rounded-r-md bg-white p-2 text-gray-900 shadow-lg transition-all duration-300 ease-in-out hover:bg-gray-200 data-[collapsed=true]:rounded-md data-[collapsed=true]:bg-gray-200 data-[collapsed=true]:p-1"
//             data-collapsed="false"
//           >
//             <ChevronRightIcon className="h-4 w-4 transition-transform data-[collapsed=true]:rotate-180" />
//           </button>
//         </div>
//         <div className="flex-1 p-6">
//           <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
//             <div className="bg-white rounded-lg shadow-lg p-6">
//               <h2 className="text-lg font-medium mb-4">Overview</h2>
//               <p>This is the overview section.</p>
//             </div>
//             <div className="bg-white rounded-lg shadow-lg p-6">
//               <h2 className="text-lg font-medium mb-4">Analytics</h2>
//               <p>This is the analytics section.</p>
//             </div>
//             <div className="bg-white rounded-lg shadow-lg p-6">
//               <h2 className="text-lg font-medium mb-4">Tasks</h2>
//               <p>This is the tasks section.</p>
//             </div>
//           </div>
//         </div>
//       </div>
//     </>
//   )
// }
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
